CREATE TABLE Ticket (
id INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
customername VARCHAR(50),
subject VARCHAR(50) NOT NULL,
body VARCHAR(200) NOT NULL,
categories VARCHAR(100) NOT NULL,
primary key (id)

);